#!/usr/bin/env python3
"""Regenerate third_party/gm8x_fix from a gm8x_fix checkout.

    python tools/update-gm8x-fix.py <path to gm8x_fix checkout>

Reads gm8x_fix's patch tables (patches.c) and patch list (gm8x_fix.c), keeps
the patches that apply to a GM8.0 runner, in gm8x_fix's order, and writes them
as C# to third_party/gm8x_fix/Gm8xFixPatches.cs. Copies gm8x_fix's LICENSE
alongside and records the upstream commit in the generated file.

Upstream: https://github.com/skyfloogle/gm8x_fix
"""

import os
import re
import shutil
import subprocess
import sys

TOKEN = r"(-?0x[0-9a-fA-F]+|-?\d+|'(?:\\.|[^'])')"
ESCAPES = {'0': 0, 'n': 10, 'r': 13, 't': 9, '\\': 92, "'": 39}


def value(s):
    if s.startswith("'"):
        c = s[1:-1]
        return ESCAPES[c[1]] if c.startswith('\\') else ord(c)
    return int(s, 0)


def literal(v):
    return '0x%x' % v if v > 255 else str(v)


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    upstream = sys.argv[1]
    out_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'third_party', 'gm8x_fix')

    patches_c = open(os.path.join(upstream, 'patches.c'), encoding='utf-8').read()
    main_c = open(os.path.join(upstream, 'gm8x_fix.c'), encoding='utf-8').read()

    patch_list = main_c[main_c.index('Patch patches[]'):]
    entries = re.findall(r'\{\.bytes = (\w+), \.name = "([^"]+)", \.type = (\w+)\}', patch_list)
    wanted = [(array, name) for array, name, _ in entries if array.endswith('_80') or array == 'mempatch']
    if not wanted:
        sys.exit('no GM8.0 patches found - has gm8x_fix changed its layout?')

    tables = {}
    for array, body in re.findall(r'PatchByte (\w+)\[\] = \{(.*?)\n\};', patches_c, re.S):
        triples = re.findall(r'\{\s*' + TOKEN + r'\s*,\s*' + TOKEN + r'\s*,\s*' + TOKEN + r'\s*\}', body)
        if len(triples) != body.count('{'):
            sys.exit('could not parse every entry of %s' % array)
        tables[array] = [tuple(value(x) for x in t) for t in triples]

    try:
        commit = subprocess.run(['git', '-C', upstream, 'rev-parse', 'HEAD'],
                                capture_output=True, text=True, check=True).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        commit = 'unknown'

    lines = [
        '// <auto-generated>',
        '// Generated by tools/update-gm8x-fix.py from gm8x_fix',
        '// (https://github.com/skyfloogle/gm8x_fix), commit %s.' % commit,
        '// Only the patches that apply to a GM8.0 runner are kept, in gm8x_fix\'s order.',
        '// Do not edit by hand; rerun the script to update.',
        '//',
        '// Copyright (c) 2019 Floogle. MIT licensed: see LICENSE in this directory.',
        '// </auto-generated>',
        '',
        'namespace Gm8Builder.Pe;',
        '',
        'public static partial class Gm8xFix',
        '{',
        '    /// <summary>The gm8x_fix commit these tables were generated from.</summary>',
        '    public const string UpstreamCommit = "%s";' % commit,
        '',
        '    /// <summary>Each patch: name, then (file offset, original byte, patched byte) triples, ending at -1.</summary>',
        '    private static readonly (string Name, int[] Bytes)[] Patches =',
        '    [',
    ]
    for array, name in wanted:
        flat = [v for triple in tables[array] for v in triple]
        lines.append('        ("%s", [' % name)
        for i in range(0, len(flat), 24):
            lines.append('            ' + ', '.join(literal(v) for v in flat[i:i + 24]) + ',')
        lines.append('        ]),')
        print('%-45s %4d bytes' % (name, len(tables[array]) - 1))
    lines += ['    ];', '}', '']

    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, 'Gm8xFixPatches.cs'), 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines))
    shutil.copyfile(os.path.join(upstream, 'LICENSE'), os.path.join(out_dir, 'LICENSE'))
    print('wrote third_party/gm8x_fix from commit %s' % commit)


if __name__ == '__main__':
    main()
